#!/bin/bash

set -e
set -x

mkdir build
cd build
cmake .. -DPORT=GTK -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja -DENABLE_JIT=OFF -DENABLE_C_LOOP=ON -DENABLE_SAMPLING_PROFILER=OFF -DENABLE_WEBASSEMBLY=OFF -DUSE_SYSTEM_MALLOC=ON -DUSE_LIBBACKTRACE=OFF -DUSE_LIBHYPHEN=OFF -DENABLE_GAMEPAD=OFF -DENABLE_MINIBROWSER=ON -DENABLE_DOCUMENTATION=OFF -DENABLE_WEBDRIVER=OFF -DUSE_WOFF2=OFF -DUSE_GTK4=ON -DENABLE_JOURNALD_LOG=OFF -DDEVELOPER_MODE=ON -DDEVELOPER_MODE_FATAL_WARNINGS=OFF -DENABLE_XSLT=OFF -DENABLE_SPELLCHECK=ON -DUSE_JPEGXL=OFF -DUSE_AVIF=OFF -DENABLE_BUBBLEWRAP_SANDBOX=OFF

set +x

echo "SUCCESS"
echo "Now do (cd build && ninja) to build."
