#!/bin/bash
#
# Copyright (c) 2025 Epic Games, Inc. All Rights Reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY EPIC GAMES, INC. ``AS IS AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL EPIC GAMES, INC. OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e

# Marker used to identify test files we created
MARKER="# GENERATED BY FIL-C KRB TEST - Safe to delete"

# Test realm name
REALM="TEST.REALM"

# Get hostname for service principals
HOSTNAME=$(hostname)

# Current user for creating principals
CURRENT_USER=${SUDO_USER:-$(whoami)}

echo "================================================================================"
echo "                        Fil-C Kerberos Test Setup"
echo "================================================================================"
echo
echo "This script sets up a TEST Kerberos realm using Fil-C-built Kerberos."
echo
echo "IMPORTANT: This is for TESTING only, not production use!"
echo
echo "********************************************************************************"
echo "                                  SAFETY"
echo "********************************************************************************"
echo "This script will ONLY modify files it previously created (marked with a"
echo "special comment). It will REFUSE to touch any existing production Kerberos"
echo "configuration."
echo "********************************************************************************"
echo

# Check if running as root
if [ $(id -u) -ne 0 ]; then
    echo "ERROR: This script must be run as root (use sudo)."
    exit 1
fi

# Function to check if a file is safe to modify
check_safe_to_modify() {
    local file=$1
    if [ ! -f "$file" ]; then
        # File doesn't exist - safe to create
        return 0
    fi

    # Check if file has our marker
    if head -n 1 "$file" | grep -q "GENERATED BY FIL-C KRB TEST"; then
        return 0  # Safe - we created it
    else
        return 1  # Unsafe - not our file
    fi
}

# Check files before doing anything
FILES_TO_CHECK=(
    "/etc/krb5.conf"
    "/var/lib/krb5kdc/kdc.conf"
    "/var/lib/krb5kdc/kadm5.acl"
)

UNSAFE_FILES=()
for file in "${FILES_TO_CHECK[@]}"; do
    if ! check_safe_to_modify "$file"; then
        UNSAFE_FILES+=("$file")
    fi
done

if [ ${#UNSAFE_FILES[@]} -gt 0 ]; then
    echo "ERROR: Found existing Kerberos configuration files that were NOT created by"
    echo "this script. Refusing to modify to protect your production setup."
    echo
    echo "Existing files found:"
    for file in "${UNSAFE_FILES[@]}"; do
        echo "  - $file"
    done
    echo
    echo "To use this script, either:"
    echo "  1. Manually back up and remove these files"
    echo "  2. Add this comment as the FIRST line of each file:"
    echo "     $MARKER"
    echo
    exit 1
fi

# Show what we'll do
echo "This script will:"
echo "  - Create /etc/krb5.conf (client configuration)"
echo "  - Create /var/lib/krb5kdc/ directory structure"
echo "  - Create /var/lib/krb5kdc/kdc.conf (KDC configuration)"
echo "  - Create /var/lib/krb5kdc/kadm5.acl (admin ACL)"
echo "  - Initialize Kerberos database at /var/lib/krb5kdc/principal*"
echo "  - Create test principals:"
echo "      - $CURRENT_USER@$REALM (user)"
echo "      - $CURRENT_USER/admin@$REALM (admin)"
echo "      - host/$HOSTNAME@$REALM (SSH service)"
echo "  - Extract host keytab to /etc/krb5.keytab"
echo
echo "Realm: $REALM"
echo "Hostname: $HOSTNAME"
echo "User: $CURRENT_USER"
echo
echo "Type YES (in all caps) to proceed, or anything else to abort:"
read response

if [ "$response" != "YES" ]; then
    echo "Setup aborted."
    exit 1
fi

echo
echo "Setting up Kerberos test realm..."
echo

# Create /etc/krb5.conf
echo "Creating /etc/krb5.conf..."
cat > /etc/krb5.conf <<EOF
$MARKER
[libdefaults]
    default_realm = $REALM
    default_keytab_name = FILE:/etc/krb5.keytab
    dns_lookup_realm = false
    dns_lookup_kdc = false

[realms]
    $REALM = {
        kdc = localhost
        admin_server = localhost
    }

[domain_realm]
    .localhost = $REALM
    localhost = $REALM
    .$HOSTNAME = $REALM
    $HOSTNAME = $REALM
EOF

# Create /var/lib/krb5kdc/ directory
echo "Creating /var/lib/krb5kdc/ directory..."
mkdir -p /var/lib/krb5kdc
chmod 700 /var/lib/krb5kdc

# Create /var/lib/krb5kdc/kdc.conf
echo "Creating /var/lib/krb5kdc/kdc.conf..."
cat > /var/lib/krb5kdc/kdc.conf <<EOF
$MARKER
[kdcdefaults]
    kdc_ports = 88
    kdc_tcp_ports = 88

[realms]
    $REALM = {
        database_name = /var/lib/krb5kdc/principal
        admin_keytab = FILE:/var/lib/krb5kdc/kadm5.keytab
        acl_file = /var/lib/krb5kdc/kadm5.acl
        key_stash_file = /var/lib/krb5kdc/.k5.$REALM
        max_renewable_life = 7d
        max_life = 1d
    }
EOF

# Create /var/lib/krb5kdc/kadm5.acl
echo "Creating /var/lib/krb5kdc/kadm5.acl..."
cat > /var/lib/krb5kdc/kadm5.acl <<EOF
$MARKER
*/admin@$REALM    *
EOF

# Initialize the Kerberos database
echo
echo "Initializing Kerberos database..."
echo "You will be prompted for a master password. For testing, any password works."
echo "(Suggestion: just use 'password')"
echo

/opt/fil/sbin/kdb5_util create -s

echo
echo "Database created successfully."
echo

# Create principals
echo "Creating Kerberos principals..."
echo
echo "Creating user principal: $CURRENT_USER@$REALM"
echo "You will be prompted to set a password for this principal."
echo "(This is your Kerberos password for testing, use something simple)"
echo

/opt/fil/sbin/kadmin.local -q "addprinc $CURRENT_USER"

echo
echo "Creating admin principal: $CURRENT_USER/admin@$REALM"
echo "(Optional - used for kadmin remote administration)"
echo

/opt/fil/sbin/kadmin.local -q "addprinc $CURRENT_USER/admin"

echo
echo "Creating host service principal: host/$HOSTNAME@$REALM"
/opt/fil/sbin/kadmin.local -q "addprinc -randkey host/$HOSTNAME"

# Also create localhost principal for convenience
echo "Creating host service principal: host/localhost@$REALM (for convenience)"
/opt/fil/sbin/kadmin.local -q "addprinc -randkey host/localhost"

# Extract keytabs
echo
echo "Extracting host keytab to /etc/krb5.keytab..."
/opt/fil/sbin/kadmin.local -q "ktadd -k /etc/krb5.keytab host/$HOSTNAME"
/opt/fil/sbin/kadmin.local -q "ktadd -k /etc/krb5.keytab host/localhost"

chmod 600 /etc/krb5.keytab

echo
echo "================================================================================"
echo "                   Kerberos Test Realm Setup Complete!"
echo "================================================================================"
echo
echo "Configuration files created:"
echo "  - /etc/krb5.conf"
echo "  - /var/lib/krb5kdc/kdc.conf"
echo "  - /var/lib/krb5kdc/kadm5.acl"
echo "  - /etc/krb5.keytab"
echo
echo "Kerberos database:"
echo "  - /var/lib/krb5kdc/principal*"
echo
echo "Principals created:"
echo "  - $CURRENT_USER@$REALM (your user)"
echo "  - $CURRENT_USER/admin@$REALM (admin)"
echo "  - host/$HOSTNAME@$REALM (SSH service)"
echo "  - host/localhost@$REALM (SSH service)"
echo
echo "================================================================================"
echo "                              Next Steps"
echo "================================================================================"
echo
echo "1. Start the KDC and admin server:"
echo "   Terminal 1: sudo /opt/fil/sbin/krb5kdc -n"
echo "   Terminal 2: sudo /opt/fil/sbin/kadmind -nofork"
echo
echo "2. Get a Kerberos ticket:"
echo "   /opt/fil/bin/kinit $CURRENT_USER"
echo
echo "3. Verify the ticket:"
echo "   /opt/fil/bin/klist"
echo
echo "4. Test GSSAPI SSH (make sure GSSAPIAuthentication is enabled in sshd_config):"
echo "   ssh -p 10022 $HOSTNAME"
echo "   (Should log in without asking for a password!)"
echo
echo "5. To clean up later, run:"
echo "   sudo rm -rf /etc/krb5.conf /etc/krb5.keytab /var/lib/krb5kdc"
echo
echo "See setup_krb.md for detailed documentation."
echo
echo "================================================================================"
